version: '2'
services:
  mysql:
    restart: unless-stopped
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASS: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - educaas_db:/var/lib/mysql
  rancher:
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9345:9345" 
    image: rancher/server:stable
    command: --advertise-address ${MACHINE_IP}
    environment:
      CATTLE_DB_CATTLE_MYSQL_HOST: mysql
      CATTLE_DB_CATTLE_MYSQL_PORT: 3306
      CATTLE_DB_CATTLE_USERNAME: ${DB_USER}
      CATTLE_DB_CATTLE_PASSWORD: ${DB_PASSWORD}
      CATTLE_DB_CATTLE_MYSQL_NAME: ${DB_NAME}
    env_file: .env
  lets-nginx:
    links:
      - rancher:backend
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
      - UPSTREAM=rancher:8080
    ports:
      - 80:80
      - 443:443
    image: smashwilson/lets-nginx
    env_file: .env
volumes:
  educaas_db:
