version: '2'
services:
  mysql:
    restart: unless-stopped
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - educaas_db:/var/lib/mysql

  db-backup:
    restart: unless-stopped
    image: deitch/mysql-backup
    links:
      - mysql:db
    environment:
      - DB_DUMP_FREQ= ${DB_DUMP_FREQ}
      - DB_DUMP_BEGIN= ${DB_DUMP_BEGIN}
      - DB_DUMP_TARGET=/db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file: .env

  rancher:
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9345:9345" 
      - "9108:9108"
    image: rancher/server:v1.5.9
    command: --advertise-address ${MACHINE_IP} --db-host mysql --db-port 3306 --db-name ${DB_NAME} --db-pass ${DB_PASSWORD} --db-user ${DB_USER}
    environment: 
      - CATTLE_PROMETHEUS_EXPORTER=${CATTLE_PROMETHEUS_EXPORTER}
    env_file: .env
    links: 
      - mysql:mysql

  lets-nginx:
    links:
      - rancher:backend
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
      - UPSTREAM=rancher:8080
    ports:
      - 80:80
      - 443:443
    image: smashwilson/lets-nginx
    env_file: .env
    volumes:
      - educaas_certs:/etc/letsencrypt/
volumes:
  educaas_db:
  educaas_certs:
